apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::939502888007:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-QHFF9AWTH9T8
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::939502888007:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-01T12:48:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1569"
  uid: 90c62dfa-dfb8-43c8-82c5-734819061ae3
